version: 0.2

env:
    variables:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCOUNT_ID: 953422125712
        IMAGE_REPO_NAME_LIST: "ecr-php-frontend ecr-python-frontend"

phases:
    pre_build:
        commands:
            - echo "Logging in to Amazon ECR..."
            - REPOSITORY_HOST="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
            - aws --version
            - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_HOST}
            - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)
            - echo "IMAGE_TAG=${IMAGE_TAG}"

    build:
        commands:
            - echo Build start on $(date)
            - |
              for IMAGE_REPO_NAME in ${IMAGE_REPO_NAME_LIST}; do
                docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
                docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_HOST}/${IMAGE_REPO_NAME}:${IMAGE_TAG}
                docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_HOST}/${IMAGE_REPO_NAME}:latest
              done

    post_build:
        commands:
            - echo Build completed on $(date)
            - printf '[' > imagedefinitions.json
            - |
              for IMAGE_REPO_NAME in ${IMAGE_REPO_NAME_LIST}; do
                docker push ${REPOSITORY_HOST}/${IMAGE_REPO_NAME}:${IMAGE_TAG}
                docker push ${REPOSITORY_HOST}/${IMAGE_REPO_NAME}:latest
                echo "Writing image definitions file..."
                container_name="${IMAGE_REPO_NAME#ecr-}"
                printf '{"name":"%s","imageUri":"%s"}' ${container_name} ${REPOSITORY_HOST}/${IMAGE_REPO_NAME}:${IMAGE_TAG} >> imagedefinitions.json
              done
            - printf ']' >> imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json