name: Free Local AI Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
  
      - name: Install transformers
        run: |
          pip install openai
          pip install PyGithub
      
      - name: Local AI Review
        run: |
          python ./.github/workflows/scripts/local_ai_review.py
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: "Yoshiya-H/ITnews"
          PR_NUMBER: ${{ github.event.number }}
